// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrG3rP2EG09QfQ761SbjOePtg-biIT4Rc',
    appId: '1:137812074853:web:57c0da28077b3528f1818c',
    messagingSenderId: '137812074853',
    projectId: 'students-50df7',
    authDomain: 'students-50df7.firebaseapp.com',
    storageBucket: 'students-50df7.appspot.com',
    measurementId: 'G-80S1GKXCQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_vnYfj625w-IsSprFHwDH7YNXr0KbxfI',
    appId: '1:137812074853:android:41be8ad6aa6e6012f1818c',
    messagingSenderId: '137812074853',
    projectId: 'students-50df7',
    storageBucket: 'students-50df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRFbxU8wLn-23APaX6Y2zI-UYwUPUUq0',
    appId: '1:137812074853:ios:8819be4298f5c522f1818c',
    messagingSenderId: '137812074853',
    projectId: 'students-50df7',
    storageBucket: 'students-50df7.appspot.com',
    iosClientId: '137812074853-vh9uslen0ntum7hcbt6v3haas386qdid.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRFbxU8wLn-23APaX6Y2zI-UYwUPUUq0',
    appId: '1:137812074853:ios:8819be4298f5c522f1818c',
    messagingSenderId: '137812074853',
    projectId: 'students-50df7',
    storageBucket: 'students-50df7.appspot.com',
    iosClientId: '137812074853-vh9uslen0ntum7hcbt6v3haas386qdid.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );
}
