# 데이터 시각화

### 산점도(산포도)

```{r}
y <- c(1,1,2,2,3,3,4,4,5,5)
plot(y)
```

```{r}
x <- 1:10
y <- 1:10
plot(x,y)
```

```{r}
plot(y ~ x)
```

```{r}
plot(x, y,
     xlim = c(0,11),
     ylim = c(0,11)
     )
```

```{r}
seoul <- read.csv("./Data/newSeoul2019.csv")
head(seoul)
```

### 서울시 교통사고 데이터로 발생건수와 부상자수의 산포도 구하기

단, 발생건수가 150이하면 빨간색으로 초과이면 파란색으로 구분하기

```{r}
par(family="AppleGothic")
plot(seoul$발생건수, seoul$부상자수,
     col = ifelse(seoul$발생건수 <= 150, "red", "blue")
     )
```

```{r}
par(family="AppleGothic")
plot(seoul$발생건수, seoul$부상자수,
     col = ifelse(subset(seoul, 자치구명 == '강남구' && 발생건수 == max(발생건수)), "red", "blue")
     )
```

### 꺽은선 그래프

```{r}
y <- c(1,3,2,4,8,5,7,6,9)
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "l"
     )
```

### 점과 꺽은선 그래프

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "b"
     )
```

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "c"
     )
```

### 점과 꺽은선 그래프를 중첩한 그래프

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "o"
     )
```

### 수직선 그래프

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "h"
     )
```

### 왼쪽 값을 기초로한 계단 모양 그래프

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "s"
     )
```

### 오른쪽 값을 기초로한 계단 모양 그래프

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "S"
     )
```

## Line Type

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     type = "S",
     lty = 2
     )
```

# Plotting Symbol

```{r}
plot(y,
     main = "Simple Time Series",
     xlim = c(min(y) - 1, max(y) + 1),
     ylim = c(min(y) - 1, max(y) + 1),
     pch = 9,
     col = "red"
     )
```

y의 값이 0.5보다 크면 컬러는 빨간색, pch = 1, 아니면 컬러는 파란색, pch = 18

```{r}
x <- runif(1000)
y <- runif(1000)
plot(x, y,
     col = ifelse(y > 0.5, "red", "blue"),
     pch = ifelse(y > 0.5, 1, 18)
     )
```

# 선 그래프

```{r}
abc <- c(260, 300, 250, 280, 310)
def <- c(180, 200, 210, 190, 170)
ghi <- c(210, 250, 260, 210, 270)
```

```{r}
par(family="AppleGothic")
plot(abc,
     type = "o",
     col = "red",
     ylim = c(0, 400),
     axes = F,
     ann = F
     )

axis(1,
     at = 1:5,
     lab = c("서울","대전","대구","광주","원주")
     )

axis(2,
     ylim = c(0,400)
     )

title(main = "과일 판매량", col.main = "red")
title(xlab = "지역", col.lab = "blue")
title(ylab = "판매량", col.lab = "green")

lines(def,
      type = "o",
      pch = 22,
      col = "green",
      lty = 2
      )

lines(ghi,
      type = "o",
      pch = 22,
      col = "blue",
      lty = 2
      )

legend(4, 400,
       c("야구장","축구장","해변가"),
       col = c("red","green","blue"),
       pch = c(21,22,22),
       lty = c(1,2,2),
       cex = 0.7
      )
```

# 막대 그래프

```{r}
x <- 1:6
barplot(x,
        main = "1~6",
        xlab = "Sales",
        ylab = "Amounts",
        names = c("A","B","C","D","E","F"),
        col = c("red",rep("blue",5))
        )
```

```{r}
x <- matrix(1:6, 3, 2)
par(family="AppleGothic")
rownames(x) <- c("A","B","C")
barplot(x,
        ylim = c(0, 12 ),
        beside = T,
        names = c("Korea", "America"),
        main = "수출량",
        xlab = "국가",
        ylab = "빈도수",
        col = c("red","green","blue"),
        legend.text = T
        )
```

```{r}
barplot(abc,
        main = "Baseball Sales",
        xlab = "Sesson",
        ylab = "Sales",
        names = c("Jan","Feb","Mar","Apr","May"),
        col = c("red",rep("blue", length(abc) - 1)),
        density = c(10, 30, 50, 40, 10),
        border = c("red",rep("blue", length(abc) - 1))
        )
```

# 학력별 점수 차이

```{r}
data <- read.csv("./Data/education.csv", header = F)
head(data)
```

```{r}
str(data)
```

V1 : 남, 여

V2 : 점수

V3 : 국, 영, 수

V4 : 초, 중, 고, 대, 원

```{r}
sum(is.na(data))
```

```{r}
table(data$V1)
table(data$V2)
table(data$V3)
table(data$V4)
```

```{r}
data$V1 <- factor(data$V1, levels = 1:2, labels = c("남", "여"))
data$V3 <- factor(data$V3, levels = 1:3, labels = c("국어","영어","수학"))
data$V4 <- factor(data$V4, levels = 1:5, labels = c("초","중","고","대","원"))
```

```{r}
head(data)
```

```{r}
str(data)
```

```{r}
colnames(data) <- c("성별","점수","과목","학력")
head(data)
```

```{r}
table(data$점수)
```

### 점수별 빈도수를 막대그래프로 표현 하세요

```{r}
barplot(table(data$점수))
```

### 성별 학력별 빈도수를 표현

```{r}
par(family="AppleGothic")
barplot(table(data$학력, data$성별),
        beside = T
        )
```

## 년도별 분기별 비교 막대 그래프

```{r}
chart_data <- c(305,450,320,460,330,480,380,520)
names(chart_data) <- c("2017년 1분기", "2018년 1분기",
                       "2017년 2분기", "2018년 2분기",
                       "2017년 3분기", "2018년 3분기",
                       "2017년 4분기", "2018년 4분기"
                       )
chart_data
```

```{r}
par(family="AppleGothic")
barplot(chart_data,
        main = "2017년도 2018년도 분기별 매출 현황 비교",
        xlim = c(0, 600),
        col = rainbow(length(chart_data)),
        ylab = "년도별 분기현황",
        xlab = "매출액(단위:만원)",
        horiz = T,
        cex.names = 0.2,
        space = 0.5
        )
```

```{r}
par(family="AppleGothic")
barplot(chart_data,
        main = "2017년도 2018년도 분기별 매출 현황 비교",
        xlim = c(0, 600),
        col = c("red","blue"),
        ylab = "년도별 분기현황",
        xlab = "매출액(단위:만원)",
        horiz = T,
        cex.names = 0.2,
        space = c(2,0.5)
        )
```

# 1940년 미국 버지니아주 하위계층 사망 비율

```{r}
VADeaths
```

```{r}
str(VADeaths)
```

```{r}
str(data.frame(VADeaths))
```

```{r}
barplot(VADeaths,
        beside = T,
        col = rainbow(5),
        ylim = c(0, 80),
        )

legend(7, 80,
       c(rownames(VADeaths)[1:5]),
       fill = rainbow(5),
       cex = 0.8
      )
```

# 파이차트

```{r}
T_Sales <- c(210,110,400,550,600,130)
par(family="AppleGothic")
week <- c("월","화","수","목","금","토")
ratio <- T_Sales / sum(T_Sales) * 100
label <- paste(week, "\n", ratio, "%")

pie(T_Sales,
    main = "영업 실적 파이 차트",
    col = rainbow(length(T_Sales)),
    labels = label
    )
```

# 3D Pie Chart

```{r}
library(plotrix)

T_Sales <- c(210,110,400,550,600,130)
par(family="AppleGothic")
week <- c("월","화","수","목","금","토")
ratio <- T_Sales / sum(T_Sales) * 100
label <- paste(week, "\n", ratio, "%")

pie3D(T_Sales,
    main = "영업 실적 파이 차트",
    col = rainbow(length(T_Sales)),
    labels = label,
    labelcex = 0.8,
    explode = 0.05
    )
```
