# 데이터 시각화 2

### 선굵기 변경하기

```{r}
x <- c(1,3,5,2,9,10)
plot(x,
     type = "b",
     col = c(rep("black",5),"blue"),
     lwd = c(rep("1",5),"3")
     )
```

### 한 화면에 차트 여러개 그려서 비교하기

```{r}
price <- runif(10, 1, 100)
par(mfrow = c(2,2))
plot(price, type = "l")
plot(price, type = "o")
plot(price, type = "h")
plot(price, type = "s")
```

### pch 속성으로 그리기

```{r}
par(mfrow = c(2,2))
plot(price, type="o", pch=5)
plot(price, type="o", pch=15)
plot(price, type="o", pch=25, col="blue ")
plot(price, type="o", pch=c(rep(20,8),15,15),
                      col="orange",
                      cex=c(rep(1,8),3,1)
     )
```

### 중첩 자료 시각화

```{r}
x <- c(1,2,3,4,2,4)
y <- rep(2,6)
plot(x,y)
```

```{r}
table(x,y)
```

##### Method #1

```{r}
xy.df <- as.data.frame(table(x,y))
xy.df
```

```{r}
plot(x,y,
     pch=15,
     cex=2*xy.df$Freq
     )
```

##### Method #2

```{r}
x <- c(1,1,1,2,2,2,2,2,2,3,3,4,5,6)
y <- c(1,1,4,2,3,2,2,2,3,2,1,1,1,1)
zz <- data.frame(x,y)
sunflowerplot(zz)
```

##### sunflowerplot으로 iris의 sepal.length와 sepal.width의 산포도 그리기

```{r}
sepal <- data.frame(iris$Sepal.Length,iris$Sepal.Width)
sunflowerplot(sepal)
```

### chart 2개를 겹쳐서 출력하기

```{r}
x <- 1:10
mycol <- rgb(0,0,1,seq(0, 1,0.1))
dotchart(x,
         col="red"
         )
par(new=T)
barplot(x,
        col=mycol
        )
```

# 상자 수염 그래프

: 이상치 확인

```{r}
abc <- c(110,300,150,280,310)
boxplot(abc,
        col="yellow",
        horizontal = T)
```

```{r}
def <- c(1,1,1,1,1,2,5)
summary(def)
```

```{r}
boxplot(def)
```

### 자동차의 제동거리

```{r}
head(cars)
```

```{r}
str(cars)
```

```{r}
plot(cars$speed,cars$dist)
```

```{r}
hist(cars$dist)
```

```{r}
boxplot(cars$dist)
```

# 차트 디자인

```{r}
par(family="AppleGothic")

x <- c(1,3,6,8,9)
y <- c(12,56,78,32,9)
plot(x,y)

# (3,3)과 (4,4)를 연결하는 선분 그리기
segments(6,78,8,32, col="red")

# 화살표 그리기
arrows(3,56,1,12) 

# 글자쓰기
text(4,40, "This is a 샘플", srt = 50)

# 테두리 활용하기
mtext("Character", side = 4, adj = 0)

# 테두리 그리기
box(lty = 1, col = "red")

# 사각형 그리기
rect(4,20,6,30, density = 10, col = "red")

# x축 추가, y축의 40 위치에 0~10까지 표시하고 색은 파란색
axis(1, pos = 40, at = 0:10, col = "blue")

# y축 추가, x축의 6위치에 20~60까지 표시하고 색은 노란색
axis(2, pos = 6, at = 20:60, col = "yellow")
```

# 투표수가 높은 시군구의 후보별 득표수의 막대그래프에 시군구별 투표수 표시하기

```{r}
library(dplyr)
 election <- read.csv("./Data/election_2022_job.csv")
 election_top <- arrange(election,desc(투표수))[1:5,]
 election_top_matrix <- as.data.frame(t(election_top[1:5,5:7]))
 election_top_matrix[0:2,1]
 election_top_matrix
```

```{r}
par(family="AppleGothic")
options(scipen = 100)
barplot(t(election_top[1:5,5:7]),
        col = c("skyblue","red","yellow"),
        ylim = c(0,600000),
        legend.text = T,
        name = paste(election_top$광역시도,election_top$시군구),
        cex.axis = 0.55,
        cex.names = 0.7
        )
line <- 0.75
#for (i in 1:ncol(election_top_matrix)) {
#  data = sum(election_top_matrix[,i])
#  text(line, data + 15000, data, cex=0.8)
#  line = line + 1.2
#}
data <- c()
for (i in 1:ncol(election_top_matrix)) {
  for(j in 1:nrow(election_top_matrix)) {
    data <- round(election_top_matrix[j,i] / sum(election_top_matrix[,i]) * 100,2)
    y <- rbind(election_top_matrix[0:(j-1),i],election_top_matrix[j,i]/2)
    text(line, sum(y), paste(data,"%"), cex=0.8)
  }
  line = line + 1.2
}
```

### gplot()을 이용한 산점도

```{r}
install.packages("ggplot2")
library(ggplot2)
```

```{r}
qplot(Sepal.Length, Petal.Length, data = iris,
      col=Species,
      size=Petal.Width
      )
```

# 수학 함수의 시각화

y = x\^2

```{r}
f <- function(x) {
  y = x ^ 2
  return(y)
}
```

```{r}
x <- 1:3
f(x)
```

```{r}
x <- seq(-5,5,0.1)
plot(x, f(x),
     type = "l"
     )
```

y = x\^2 + 2x + 3

```{r}
f <- function(x) {
  y = x ^ 2 + (2*x) + 3
  return(y)
}
```

```{r}
plot(x, f(x),
     type = "l"
     )
```
