# 인공신경망을 이용한 평균 예측율 구하기

```{r}
library(nnet)
library(caret)
```

```{r}
nnetFun <- function(n) {
  for(i in 1:n) {
    if(i == 1) {
      resultVec = c()
    }
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset(data.test, select = -Species)
    y <- data.test$Species
    model.nnet <- nnet(Species ~ ., data = data.train, size = 3)
    pred.nnet <- predict(model.nnet, x, type = "class")
    resultVec = append(resultVec, mean(pred.nnet == y))
  }
  
  cat("---------------------\n")
  cat("예측율 \n")
  cat(resultVec, "\n")
  cat("---------------------\n")
  cat("평균예측율 : ", mean(resultVec), "\n")
  cat("---------------------\n")
}

```

```{r}
nnetFun(10)
```

### randomForest의 편균 예측율 함수 구하기

```{r}
rfFun <- function(n) {
  for(i in 1:n) {
    if(i == 1) {
      resultVec = c()
    }
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset(data.test, select = -Species)
    y <- data.test$Species
    model.nnet <- randomForest(Species ~ ., data = data.train, size = 3)
    pred.nnet <- predict(model.nnet, x, type = "class")
    resultVec = append(resultVec, mean(pred.nnet == y))
  }
  
  cat("---------------------\n")
  cat("예측율 \n")
  cat(resultVec, "\n")
  cat("---------------------\n")
  cat("평균예측율 : ", mean(resultVec), "\n")
  cat("---------------------\n")
}
```

```{r}
rfFun(10)
```

### svm의 평균 예측율 함수 구하기

```{r}
svmFun <- function(n) {
  for(i in 1:n) {
    if(i == 1) {
      resultVec = c()
    }
    samp <- createDataPartition(iris$Species, p=0.7, list=F)
    data.train <- iris[samp,]
    data.test <- iris[-samp,]
    x <- subset(data.test, select = -Species)
    y <- data.test$Species
    model.nnet <- svm(Species ~ ., data = data.train, size = 3)
    pred.nnet <- predict(model.nnet, x, type = "class")
    resultVec = append(resultVec, mean(pred.nnet == y))
  }
  
  cat("---------------------\n")
  cat("예측율 \n")
  cat(resultVec, "\n")
  cat("---------------------\n")
  cat("평균예측율 : ", mean(resultVec), "\n")
  cat("---------------------\n")
}
```

```{r}
svmFun(10)
```
